### ISSUE TITLE
Proteore.org: Improve the configuration of the VM  

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#178]
Configurer disk space allocation (currently 40 Go including 95% occupied by soft/lib/dependencies environment) pour avoir une config plus musclée permettant le passage à l'échelle

**Comment by yvandenb** [comment]
@vloux : I'm not sure => can we closed this issue ?

**Comment by vloux** [comment]
Yes. Will be solved by using usegalaxy.fr. If needed, use proteore-migale for trainings
