### ISSUE TITLE
ProteoRE: updating tools name and hierarchy of the Tool panel 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#207]
Hiérarchie ProteoRE et hiérarchie "Galaxy-P tools" (si question passe me voir)

1. ProteoRE
Data Manipulation
ID Converter (Human, Mouse, Rat)
Filter by keywords and/or numerical value
Venn diagram [JVenn]
HeatMap (Cluster and visualize the results)

Human Annotation
Get expression profiles by (normal or tumor) tissue/cell type [Human Protein Atlas]
Add expression data (RNAseq or Immuno-assays)[Human Protein Atlas]
Add protein features [neXtProt]
Get MS/MS observations in tissue/fluid [Peptide Atlas]
Build tissue-specific expression dataset [Human Protein Atlas](no input required)

Mouse Annotation
Add protein features (Mouse) [UniProt]

Go terms Analysis
Statistical analysis of functional profiles (Human, Mouse) [goProfiles]
Enrichment analysis for Gene Ontology (Human, Mouse, Rat)[topGO]
GO terms classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]

Pathway Analysis
Query pathway database [Reactome]
Pathways identification and coverage [KEGG]
Pathways visualization of (differentially expressed) genes/proteins [KEGG]
Build Protein-Protein interaction network [BioGRID, BioPlex, HuMAP] 

2. Galaxy-P tools 
QuanTP Correlation between protein and transcript abundances

**Sample Specific DB generation**
CustomProDB Generate protein FASTAs from exosome or transcriptome data
PSM to SAM Generate SAM files from PSMs.
**NB:** tous ces outils existants ont été placés par erreur et doivent être retirés:
MPileup call variants
Concat fasta files Concatenates fasta files you select from your history
Regex Find And Replace
Column Regex Find And Replace
bcftools call SNP/indel variant calling from VCF/BCF
bcftools mpileup Generate VCF or BCF containing genotype likelihoods for one or multiple alignment (BAM or CRAM) files
bcftools view VCF/BCF conversion, view, subset and filter VCF/BCF files

**Sequence Database Tools**
Protein Database DownloaderNB: 
FASTA Merge Files and Filter Unique Sequences Concatenate FASTA database files together

**Protein/Peptide Search Algorithms**
Peptide Shaker Perform protein identification using various search engines based on results from SearchGUI
Search GUI Perform protein identification using various search engines and prepare results for input to Peptide Shaker

**Comment by yvandenb** [comment]
Est-ce fait? Peut-on fermer cette issue ?

**Comment by davidchristiany** [comment]
Oui, il s'agit des labels des sections dans le tool Panel
