### ISSUE TITLE
ProteoRE training material: "hands on" to be deposited in GTN 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#218]
As a reminder...durant l'ecole de Roscoff

**Comment by combesf** [comment]
The tuto for biomarker candidate identification is now on the GTN !
https://training.galaxyproject.org/training-material/topics/proteomics/

Ongoing for the proteome annotation tutorial.

**Comment by yvandenb** [comment]
Les 2 tuitos sont validés et en ligne:
https://training.galaxyproject.org/training-material/topics/proteomics/tutorials/biomarker_selection/tutorial.html

https://training.galaxyproject.org/training-material/topics/proteomics/tutorials/proteome_annotation/tutorial.html
