### ISSUE TITLE
id converter : release 10-04-19 (Human, Mus musculus, Rattus norvegicus)

### ISSUE THREAD

**Issue by davidchristiany** [ifb-git/ProteoRE#226]
Mettre à jour les fichiers refs pour la convertion des ids avec la release du 10 avril.

**Comment by yvandenb** [comment]
Pour rappel, chaque entrée Uniprot possède 2 identifiants; Un UP Accession Number (e.g. P09876) et un Uniprot_ID (e.g. AMYB_HUMAN); avec la nvelle release des amppings, on ne gère que les "reviewed", on devrait donc avoir 1 UP_AccNum associé à 1 UP_ID; or pour le moment ci-dessous: 
![image](https://user-images.githubusercontent.com/29478729/59441186-7a040380-8df8-11e9-8056-f93bb8ad7f6c.png)
En ne considérant que les entries "reviewed" on devrait avoir une relation one-to-one pour chaque duplet [AccNum-UP_ID]; cela suggère que les UP_ID "unreviewed" sont tjrs présents pour le moment...to be fixed...

**Comment by davidchristiany** [comment]
J'ai mis à jour le data manager et généré un nouveau fichier ref pour id converter sur proteore-migale.
Les uniprot-ID associés a des uniprot-AC non reviewed ne sont plus affichés.

**Comment by davidchristiany** [comment]
Dites moi si c'est bon pour vous, une fois validé je mettrais la release 13/09/19 (Human, Mouse, Souris) dans le dossier de l'outil id_converter.

**Comment by yvandenb** [comment]
Merci David ! :-) Tests en cours sur les 3 species pour le coup for final validation (roulements de tambours) et réponse d'ici mardi je pense pour déploiement complet sur Proteore.org
En attendant pourrais-tu mettre  àjour le xml partie USerDoc, parag  
1. Input, préciser la limite de nbre d'ID en mode copy/paste
2. parameters;: UniProt ID (e.g 1433B_HUMAN) => préciser qu'il s'agit des reviewed entries également
3. "Data sources (release date)" indiquer dates exactes en accord avec repository Uniprot

**Comment by davidchristiany** [comment]
Mis à jour sur proteore-migale

**Comment by yvandenb** [comment]
Sur migale-proteore: 
History "Test_ID_converter"
Test sur un jeu d'ID souris (Wilson-foie-souris-up.txt) : item n°26 
conversion UP_AccNum -> UP_ID
![image](https://user-images.githubusercontent.com/29478729/59607505-bfd00d00-9113-11e9-8805-023b18ec8d46.png)
Un certain UP_ID sont retournées comme 'NA'; alors qu'en pratique ces UP_ID existent bel et bien dans le fichier de mapping MOUSE_10090_idmapping_selected.tab (last_release) ; par ex : 
Q9D566 | Q9D566_MOUSE
Q3V3U0 | Q3V3U0_MOUSE 
Au total sur 145 UP_ID sur 231 sont renvoyés "NA" alors qu'il semble être présent ds ce fichier source (je n'ai pas tout vérifié) : d'où ma question : quel fichier prends-tu pour faire les mappings ? 
Autre test: Pour le Rat : OK (cf item n°30); pour Homo sapiens:  

A corriger ds: 
Parameters .xml Mettre en correspondance ce qui est indiqué comme release et ce qui est donné dans la seciton USerDoc (cf ci-dessous)
![image](https://user-images.githubusercontent.com/29478729/59608743-50a7e800-9116-11e9-854c-a6a45bc27a3a.png)
 Userdoc section .xml: 
INPUT: 
Replace "The number limit of IDs allowed in copy/paste is 5000." by "in copy/paste mode, the number of IDs considered in input is limited to 5000"
"Data sources (release date)": 
"HUMAN_9606_idmapping_selected.tab (Uniprot 23/10/2018): ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/" les url indiqués ne sont pas les bons; tu parles d'une release 23/10/2018, si on clique on trouve la release actuelle come explicitement indiqué par l'URL :-/ 
idem pour le lien "Human uniprot-AC entries reviewed." qui correspond à l'instant temps t où tu cliques pas à la date où tu les as récupéré...merci d'indiquer les liens et dates exacts   
Je poursuis les vérifs de conhérence...

**Comment by davidchristiany** [comment]
Il est normal que tu ne retrouves pas tout les UP_ID comme auparavant car j'ai retiré les uniprot-ID correspondant aux uniprot-AC non reviewed comme convenu. 

J'ai modifié la doc de l'outil (proteore_migale), il y a maintenant des liens pour toutes les releases concernant les Uniprot-Ac reviewed. Tu peux vérifier, les unirpot-AC qui n'ont pas de correspondance ne font pas parti des reviewed.

Si tu relance le même job avec la release du 10/10/2018 tu auras la correspondance car cette release contient tous les uniprto-AC (pas eulement les reviewed).

**Comment by yvandenb** [comment]
>Tu peux vérifier, les unirpot-AC qui n'ont pas de correspondance ne font pas parti des reviewed.
Merci David, c'est clair désormais 👍 - Flo: il faudra à terme que l'on tranche de l'interet à ne gérer que les reviewed ou rajouter l'option (AccNum reviewed + unreviewed) - typiquement avec le dataset test souris -Wilson que j'ai utilisé, on perd 2/3 des IDs...
Pour le USerDoc c'est OK pour moi, David => tu peux (enfin) déployer sur proteore.org, merci pour ta persévérance

**Comment by davidchristiany** [comment]
J'ai déployé ID_converter et la dernière version du data manager sur proteore.org

**Comment by yvandenb** [comment]
Je laisse l'issue ouverte car 2 points en suspens pour discussion: 
- Garantir gestion des ID multiples par tous les outils (cf le tableau créé par David (cf ci-desssus post 14 May)
- reviewed vs unreviewed : pour le moment seuls les reviewed UP sont gérés, prévoit-on d'ajouter une option (reviewed + unreviewed) comme cela a été tenté?  non prioritaire mais à évaluer...
