### ISSUE TITLE
remove duplicate ids in GO terms tools

### ISSUE THREAD

**Issue by davidchristiany** [ifb-git/ProteoRE#230]
Je suis en train de voir et corriger le traitement des ids doublons dans les outils GO terms (et reactome). 
J'ai déjà corrigé les outils "cluster profiler" et "topgo" en supprimant les doublons.

En ce qui concerne goprofiles, une option existe pour supprimer les doublons "remove duplicate" (booléen). Mais en regardant le code, ce filtre n'est appliqué qu'avec des Entrez gene IDs en input (non appliqué avec des uniprot-AC).

Est-ce que je garde ce paramaètre (en le corrigeant) ? Ou par défaut je supprime tous les doublons ?

**Comment by yvandenb** [comment]
Ok to me
