### ISSUE TITLE
Proteore.org 2.0 deploiement

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#232]
On est proche de la nvlle release avec la todo list suivante
- Home page html (+ related html pages) : ongoing Yves + Valentin (parag contribution) - merci de vérifier qu'on a bien les bon codes côté Grenoble pour faire les moduifs/créatino via interfacze proteore.org
- Repasser une couche sur les tous les wrappers des outils Via GitHub: en cours YV
- vérifier tuto online est fonctionnel => avant ou après deploiement ?   

Qd ttes ces étapes amont sont réalisées, => Déploiement par David

**Comment by yvandenb** [comment]
J'ai repassé une couche sur tous les wrappers/outils; j'ai upploadé la welcome_page 2.0 html sur Github:ProteoRE/static/ et mis à jour/créer les web pages associées (mais que sur proteore.org)
Merci de bien vouloir faire le déploiement sur migale-proteore pour verif/relecture par vos soins

**Comment by davidchristiany** [comment]
J'ai mis la nouvelle page d'accueil sur proteore-migale.
Si l'ancienne page s'affiche, vider les cookies du site ou ouvrir la page avec la navigation privée.

**Comment by yvandenb** [comment]
Merci David; le formatage était vraiment bof, j'ai fait des corrections mais sans editeur wysiwyg,difficile de savoir ce que je fais :-/ bref, nvelle page à "recharger" qd tu pourras - toute amélioration étant la bienvenu, n'hesitez à corrger directement par vous mêmes,

**Comment by yvandenb** [comment]
question supp: quid du deploiement des tools avec wrapper corrigé sur migale-proteore ?

**Comment by davidchristiany** [comment]
J'ai mis à jour la page d'accueil (ne pas oublier d'effacer les cookies).
Je fais la mise à jour des outils sur proteore-migale sous peu.

**Comment by yvandenb** [comment]
Merci David !

**Comment by davidchristiany** [comment]
J'ai mis à jour tous les outils sur proteore-migale
