### ISSUE TITLE
Migale-Proteore 2.0 : bugs report 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#235]
history "TEST_PROTEORE_2"  shared with David & Flo 
En préparant ma demo pour GCC, j'ai rencontré ce bug:
![image](https://user-images.githubusercontent.com/29478729/60255112-69ab5880-98cf-11e9-86e9-9533e01c2b15.png)

**Comment by yvandenb** [comment]
Cluster_Profiler: 

- [ ] item n° 20 et 19:  je demande des "dot-plot' et j'obtiens des "bar-plot" 

- [ ] item n°16 et 15: je demande des dot-plot, j'ai des bar-plot pour GGO et des dot-plot pour les EGO

- [ ] enrichissement avec un background externe ne semble pas fonctionner (à tester + tard)

**Comment by yvandenb** [comment]
Add protein features [neXtProt] - item n°49
![image](https://user-images.githubusercontent.com/29478729/60255842-c65b4300-98d0-11e9-8f0f-f7d19dfc6f81.png)
![image](https://user-images.githubusercontent.com/29478729/60255876-d3783200-98d0-11e9-8643-ebc6388b5eb8.png)

**Comment by davidchristiany** [comment]
J'ai corrigé KEGG maps visualization, tu avais modifié le nom d'une variable (species) au lieu du nom du label.

**Comment by davidchristiany** [comment]
J'ai corrigé add protein features, tu avais supprimés la variable localization.
Je suppose que c'était pour simplifier l'IHM, comme celui de add protein features Mouse. 
Je laisse comme cela pour l'instant.

**Comment by yvandenb** [comment]
Merci bcp David..effectivement je voulais éviter d'avoir 2 boites de params à selectionner car si tu oublies de selectionner dans l'une des 2, ça ne démarre pas...mais bon on verra plus tard
toujours pour add-features-nextprot: peux-tu retirer de la data_table: la release NP 09-03-2019 (où tous les TMnber sont à "0") et qui est donc incorrect  

<param name="ref_file" type="select" label="Release of neXtProt reference file to use">
        <options from_data_table="proteore_nextprot_ref">
            <filter type="sort_by" column="0"/>
        </options>
Please, 
Je checke "Kegg_Visu"

**Comment by davidchristiany** [comment]
Concernant cluster profiler, les dot plot n'ont toujours concernés que les enrichissements.
Il n'y a jamais eu d'options dot plot pour les GGO.
Je suis d'accord que ce n'est pas clair avec l'IHM actuel.
Je suis en train d'ajouter la fonction dotplot pour les GGO.

**Comment by yvandenb** [comment]
Merci, peut-être est ce en lien avec #234 avec ce que j'ai observé dans le wrapper ?  
pour la prise en compte du background, je créée une issue, on verra ça plus tard
Enfin, j'ai mis à jour la page welcome2.0.html => merci de créer et mettre à jour une "saved pages" data-sources-2-0 sur proteore.org

**Comment by davidchristiany** [comment]
Je mets à jour la la welcome page sur proteore.org d'abord ou tu parles de proteore-migale ?

**Comment by yvandenb** [comment]
D'abord proteore-migale et sit out le monde est OK (but no feedbacks so far) sur proteore.org, merci

**Comment by yvandenb** [comment]
Après si tu veux faire les deux ou juste proteore.org, no problem ;)
restera juste à checker les "saved pages" associées...tiens moi informé, please

**Comment by davidchristiany** [comment]
J'ai fais la release 2.0 sur proteore.org:
- nouvelle welcome page
- nouvelle page "data sources "
- mise à jour de tous les outils
- mise à jour du workflow avec les nouvelles versions d'outils

**Comment by yvandenb** [comment]
Je viens de faire les tests:

- [ ] Welcome page + liens associés: OK

- [ ] Data sources: ressources PPI- Reactome mapping files: le lien https://www.reactome.org/download/current/NCBI2Reactome.txt correspond à la current release et non à la date à laquelle tu as récupéré ce fichier, merci de remplacer cet URL par la page de download https://reactome.org/download-data et d'indiquer la date de reease que tu as utilisé

- [ ] ProteoRE tools: on s'améliore d'une release à l'autre jsute 2 tools qui plantent ;-)
History "Demo_GCC2019" partagé avec David, Flo, Val

1. item n°46 Add protein features [neXtProt] : failed (see below) 
Fatal error: Exit code 1 ()
Error in read_file(args$nextprot, T) : File not found !
Calls: protein_features -> read_file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_prot_features/7caa90759aba/proteore_prot_features/tool-data/nextprot_ref_09-03-2019.tsv': No such file or directory
Execution halted

2. Add protein features [neXtProt] :  WARNING: tu t'es trompé de version NP 2019 (see mon post plus haut: " peux-tu retirer de la data_table: la release NP 09-03-2019  est incorrect (tous les TMnber sont à "0"), il faut rétablir celle de Mai/Juin 2019 - cette version de Mars: c'est vraiment le sparadrap du capitaine Haddock, merci de la faire retirer définitivement du circuit ;-)

3. Build Protein-Protein interaction network [BioGRID, BioPlex, HuMAP] : quelle que soit la source utilisée (BioGrid, bioPlex, HuMAP) failed: cf items de n°40 à 46 :
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_build_protein_interaction_maps/99f6a94c1ade/proteore_build_protein_interaction_maps/build_protein_interaction_maps.py", line 282, in <module>
    main()
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_build_protein_interaction_maps/99f6a94c1ade/proteore_build_protein_interaction_maps/build_protein_interaction_maps.py", line 248, in main
    with open(args.dict_path, 'r') as handle:
IOError: [Errno 2] No such file or directory: '/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_build_protein_interaction_maps/99f6a94c1ade/proteore_build_protein_interaction_maps/tool-data/Human_biogrid_01-03-2019.json

**Comment by davidchristiany** [comment]
J'ai corrigé add protein features et build protein protein interaction maps.
Les deux problèmes étaient liés aux data tables.
Tu peux tester maintenant.

**Comment by davidchristiany** [comment]
j'ai modifié les data sources pour reactome

**Comment by yvandenb** [comment]
OK pour les 2 tools: work fine now ! Merci !
Pour la relase date Reactome: 
![image](https://user-images.githubusercontent.com/29478729/60438195-7225cb00-9c10-11e9-9ec0-a1f45acc3c04.png)
Perfect, il manque juste l'info pour Uniprot2Reactome...
