### ISSUE TITLE
proteore.org: home page => "no acces by user" to ProteoRE's online tutorial: Annotating a protein list identified by LC-MS/MS experiment

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#237]
en partant de la home page:  http://www.proteore.org/u/proteore/p/proteore-tutorial-1-release-2-0
![image](https://user-images.githubusercontent.com/29478729/60732504-7cb2ce00-9f4a-11e9-8c4f-e6f9fb621ce7.png)

**Comment by davidchristiany** [comment]
c'est bon j'ai corrigé le problème, comme le pensait @vloux c'était certains datasets de l'historique qui n'étaient pas publique. J'avais oublié de cocher l'option "make all object public" en publiant l'historique.
