### ISSUE TITLE
Update bioconductor-org.*.eg.db to version 3.8.2

### ISSUE THREAD

**Issue by vloux** [ifb-git/ProteoRE#244]
To fix #243 : dependencies problem in goprofiles.

To be coherent require also update in topgo , cluster_profiler, GO_terms_profiles_comparison

@yvandenb , @combesf is it Ok for you ?

**Comment by yvandenb** [comment]
Fully Agree =>  who to do this ?

**Comment by combesf** [comment]
ok for me for the update

**Comment by vloux** [comment]
@yves -> to test on goprofiles on dev-migale

**Comment by yvandenb** [comment]
Tested on http://migale.jouy.inra.fr/proteore/
History "update_BioCond_Org.eg.db" shared with VL and Flo.
GoProfiles execution using "Lacombe" dataset 
Everything seems to be normal
Green light to test TopGo and ClusterProfiler?

**Comment by vloux** [comment]
updated topGO & clusterProfiler -> to Test on dev-migale 
@combesf , I let you update GO_terms_profiles_comparison ?

**Comment by yvandenb** [comment]
Many thx Valentin..everything worked fine on my side, Flo? 
Of note, once deployed on Proteore.org, please update the "data sources" webpage: http://proteore.org/u/proteore/p/data-sources-2

**Comment by combesf** [comment]
It is in progress on my side ....

**Comment by combesf** [comment]
Updated GO_terms_profiles_comparison -> to test on Proteore.org (careful: betatools section)
(updated tool is only on testTS for the moment)

**Comment by combesf** [comment]
> Many thx Valentin..everything worked fine on my side, Flo?
> Of note, once deployed on Proteore.org, please update the "data sources" webpage: http://proteore.org/u/proteore/p/data-sources-2

--> done for topGO and clusterProfiler

**Comment by yvandenb** [comment]
> Updated GO_terms_profiles_comparison -> to test on Proteore.org (careful: betatools section)
Galaxy Version 2019.09.27 => Run failed 
![image](https://user-images.githubusercontent.com/29478729/66128278-d2505280-e5ed-11e9-9da3-6784f5eee1a4.png)

**Comment by combesf** [comment]
@yvandenb 
I installed bioC-updated GO_terms_profile_comparison tool on proteore-migale --> it works for me on Human data

**Comment by yvandenb** [comment]
suite au TelCo lundi 7/10/2019: à déployer sur proteore.org + mise à jour de la page "Data sources": http://proteore.org/u/proteore/p/data-sources-2

**Comment by combesf** [comment]
I installed the new version (Sept 2019) of GO terms profiles comparison on peoteore.org (bêta tools section). 
It failed to run, error message = "DOSE package can't be loaded". 
The version called for DOSE pkg is 3.10.2, 
the same of the one for the "cluster_profiler" tool. 
Thus : @vloux could you please tell me if the update of "cluster_profiler" tool is OK on proteore [cluster_profiler tool also needs DOSE pkg] ? 
(I can install the updated cluster_profiler tool on proteore from the TS if you want)

**Comment by vloux** [comment]
Update done on proteore.org (at last !)
Il let you test it thoroughly

**Comment by yvandenb** [comment]
Tests are OK...what about GoProfile tool ?
Additional request: please, could you reorganize the tools panel accordingly ? i.e. these tools should be under the "GOterms analysis" section

**Comment by vloux** [comment]
GoProfile updated
Reorganization done
