### ISSUE TITLE
proteore.org : ID-converter bug (Unable to finish job)

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#248]
History shared with David: conversion Uniprot ID -> Entrez Gene ID + Ensembl GeneId (version Homo sapiens 08/05/2019) => Unable to finish job ?  
![image](https://user-images.githubusercontent.com/29478729/66736802-8b265500-ee6a-11e9-9847-b7d697931283.png)

**Comment by vloux** [comment]
Log file :
```
galaxy.jobs.runners.local DEBUG 2019-10-14 10:04:28,494 execution finished: /home/proteore/galaxy/database/jobs_directory/009/9550/galaxy_9550.sh
galaxy.model.metadata DEBUG 2019-10-14 10:04:28,535 setting metadata externally failed for HistoryDatasetAssociation 26274: CSV reader error - line 6530: field larger than field limit (131072)
galaxy.jobs.runners.local ERROR 2019-10-14 10:04:28,541 Job wrapper finish method failed
Traceback (most recent call last):
  File "/home/proteore/galaxy/lib/galaxy/jobs/runners/local.py", line 152, in queue_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/home/proteore/galaxy/lib/galaxy/jobs/runners/__init__.py", line 428, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/home/proteore/galaxy/lib/galaxy/jobs/__init__.py", line 1374, in finish
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/home/proteore/galaxy/lib/galaxy/datatypes/tabular.py", line 1014, in set_meta
    raise Exception('CSV reader error - line %d: %s' % (reader.line_num, e))
Exception: CSV reader error - line 6530: field larger than field limit (131072)
```

**Comment by yvandenb** [comment]
L'input file provient d'un 'cut' d'une colonne d'un output JVenn text...il y a effectivement uine palanquée de ligne surnuméraire 'NA', le retrait de ces lignes "NA" avec Filter_byKW, permet à ID-converter de s'en affranchir...réfléchir à comment améliorer ce point ?

**Comment by davidchristiany** [comment]
Je suis en train de voir quel est le problème exactement, si c'est le nombre de ligne du fichier input ou non. Une solution serait de tester avant l'import la taille du fichier (à voir). 
Ce qui est étrange c'est que le bug n'apparait pas si on prend un autre fichier ref pour la conversion d'ids.

**Comment by davidchristiany** [comment]
Le problème vient du fichier ref en lui même: "Human_id_mapping_27-05-2019.tsv " (qui à le nom de 08/05/19 sur proteore).
Le problème vient de la suppression des uniprot-AC unreviewed par des "NA" lors de la construction du fichier ref par le data manager car lors de la construction du dictionnaire de conversion à partir de ce fichier ref, les "NA" sont vu comme un id. Cet "id" est associés à tous les autres ids normalement associés aux uniprot-AC unreviewed. D'où le dépassement de la taille max du field lors de la conversion d'un 'NA' vu que toutes les veleurs normalement associés à tous les uniprot-AC unreviewed sont concaténés sur une ligne (pour les ids output choisit).

Je ne sais pas si je suis assez clair, en tout cas se problème ne concerne que le fichier ref "Human_id_mapping_27-05-2019.tsv " (qui à le nom de 08/05/19 sur proteore) lorsque l'on converti des NA car les fichiers suivant n'ont pas de NA mais une cellules vides : "" .

Je peux modifier le fichier ref en supprimant les "NA, ce qui résoudrait le problème.

**Comment by yvandenb** [comment]
>Je ne sais pas si je suis assez clair, 
De ce que je comprends, cela plaiderait pour un rétablissement de la prise en considération des "unreviewed" ? De même il n'y pas de "unreviewed" dans la release suivante 05/06/2019, on devrait donc avoir le même "bug, or ce n'est pas le cas (je viens de tester) - pas sûr d'avoir compris ? 
>Je peux modifier le fichier ref en supprimant les "NA, ce qui résoudrait le problème.
A décider en effet...

**Comment by davidchristiany** [comment]
Non on ne remettrais pas les unreviewed, les derniers fichiers refs n'ont pas ce problème, uniquement celui de 08/05/19 car il y a des "NA" à la place des id uniprot-AC unreviewed alors que dans les nouveaux fichiers refs il n'y a rien à la place des uniprot-AC unreviewed.
Ce qui provoque le bug est la présence des "NA" dans le fichiers refs.

Je propose simplement de corriger ce fichier ref.

**Comment by yvandenb** [comment]
>Je propose simplement de corriger ce fichier ref.
Agree !

**Comment by davidchristiany** [comment]
C'est fait, je mettrais à jour l'outil sur le toolshed quand j'aurais fini la nouvelle version d'id converter avec les genes names.

**Comment by yvandenb** [comment]
Dacis ongoing: to verify and to be closed

**Comment by davidchristiany** [comment]
files used by id converter have been changed and the data manager updated
