### ISSUE TITLE
Pathways identification and coverage (Proteore.org): execution halted

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#249]
history name: "Mouse_Lat_Liver_201910" shared with David
item n°8 using geneID as input (col 8) 
Fatal error: Exit code 1 ()
Error in .getUrl(url, .listParser, nameColumn = 1, valueColumn = 2) : 
  Service Unavailable (HTTP 503).
Calls: get_pathways_list -> keggLink -> .getUrl -> stop_for_status
Execution halted
![image](https://user-images.githubusercontent.com/29478729/67298470-983ae800-f4eb-11e9-8d6c-5cabdd0d66cf.png)

Changement d'URL pour KeggREST?

**Comment by davidchristiany** [comment]
l'erreur http 503 signifie "temporairement indisponible", donc cela devrait se résoudre du coté de kegg j'imagine. Je vais quand meême regarder ça pour être sur.

**Comment by davidchristiany** [comment]
C'est un problème de configuration de l'instance je pense, ce problème survient sur proteore.org et proteore-migale mais pas lorsque je fais tourner l'outil en local. Le fait de mettre l'outil dans la whitelist ne change rien. Il y a surement eu un changement de configuration qui a fermé un port ou quelque chose du genre.

**Comment by yvandenb** [comment]
Oui, c'est mon feeling aussi...connait-on le port number - par ex un moyen de tester via un 'tcpdump' - ? Une piste serait de voir si la config du proxy du serveur pour flux sortants (ou sinon celle du firewall) a changé ? je mets Valentin dans la boucle...

**Comment by vloux** [comment]
[proteore@proteore tmp]$ source  /home/proteore/galaxy/database/dependencies/_conda/bin/activate
(root)
 [proteore@proteore tmp]$ conda activate /home/proteore/galaxy/database/dependencies/_conda/envs/__bioconductor-keggrest@1.18.0
(__bioconductor-keggrest@1.18.0) [proteore@proteore tmp]$ R

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R est un logiciel libre livré sans AUCUNE GARANTIE.
Vous pouvez le redistribuer sous certaines conditions.
Tapez 'license()' ou 'licence()' pour plus de détails.

R est un projet collaboratif avec de nombreux contributeurs.
Tapez 'contributors()' pour plus d'information et
'citation()' pour la façon de le citer dans les publications.

Tapez 'demo()' pour des démonstrations, 'help()' pour l'aide
en ligne ou 'help.start()' pour obtenir l'aide au format HTML.
Tapez 'q()' pour quitter R.

> library(KEGGREST)

> listDatabases()

 [1] "pathway"  "brite"    "module"   "ko"       "genome"   "vg"
 [7] "ag"       "compound" "glycan"   "reaction" "rclass"   "enzyme"
[13] "disease"  "drug"     "dgroup"   "environ"  "genes"    "ligand"
[19] "kegg"
>
>
>
> org <- keggList("organism")
Error in file(con, "r") :
  cannot open the connection to 'http://rest.kegg.jp/list/organism'
De plus : Warning message:
In file(con, "r") :
  cannot open URL 'https://blackhole.dsi.inra.fr/': HTTP status was '503 Service Unavailable'


Bloquage du site par le cache INRA.
J'ai déclaré l'incident ( INC0131631 )et demandé une explication sur le changement de politique.

**Comment by yvandenb** [comment]
vous avez embauché le DSI du CEA? :) Merci Valentin...

**Comment by vloux** [comment]
Résolu
