### ISSUE TITLE
Pathways visualization: proteore.org Fatal error: Exit code 1 ()

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#251]
History "Mouse_Lat_Liver_201910" shared item n°61 et 62
![image](https://user-images.githubusercontent.com/29478729/67397771-fa5a2280-f5a9-11e9-9fed-af83efefe8e7.png)
toutes les cartes KEGG demandées n'ont pas pu être produites en png (seules 15 sur 30 sont construites): see item n°61 content

**Comment by vloux** [comment]
Only O's may be mixed with negative subscripts -> ca ne vient pas des données en entrée ?

**Comment by yvandenb** [comment]
Voir si bug reproductible: Tester la même version de PathView avec le même dataset sous RStudio...

**Comment by combesf** [comment]
I can't see the history "Mouse_Lat_Liver_201910" neither on proteore.org nor on proteore-migale : ?

**Comment by yvandenb** [comment]
oops my bad => now shared with you (available from proteore.org) - see most recent items in the history

**Comment by vloux** [comment]
Errro on Kegg side. 401/404
