### ISSUE TITLE
Proteore.org: tool installation "volcanoplot"

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#252]
Pour les besoins du workflow: "differential analysis" - how to à discuter 
here: https://toolshed.g2.bx.psu.edu/repository?repository_id=1ddf67f618bd13e7

**Comment by combesf** [comment]
installed on migale proteore

**Comment by yvandenb** [comment]
Testé sous Migale-Proteore => peut-être déployé sous Proteore.org dans la rubrique "DATA MANIPULATION" ; cette section pourrait être renommée "DATA MANIPULATION & VISUALIZATION" : à décider ensemble...

**Comment by combesf** [comment]
just deploy volcanoplot betweeen venn diag and heatmap
**volcano plot** create a volcano plot

**Comment by combesf** [comment]
Ongoing. But it seems it does not install correctly on proteore.org

**Comment by combesf** [comment]
Done.
