### ISSUE TITLE
Proteore.org : Cluster Profiler DOSE pkg could not be loaded

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#254]
History "imported: Syn_SUMO2_vs_Bckg_180919" shared (feedbacks from Carole Wizdek)
items n° 57
Fatal error: Exit code 1 ()
Error: package ‘DOSE’ could not be loaded
Execution halted

**Comment by vloux** [comment]
Resolved.

**Comment by yvandenb** [comment]
Thx, I send a e-mail to carole
