### ISSUE TITLE
proteore.org: ClusterProfiler inconsistent results ?  

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#257]
In relation with email 21th Nov sent to Flo : 
Graphical result are not in agreement with textual results 
see history imported: Syn_SUMO2_vs_Bckg_180919
item n° 64 et 65
See discrepancies between GGO_MF barplot
![image](https://user-images.githubusercontent.com/29478729/70068994-4d83b400-15f1-11ea-8ce6-6e3b6b7eac90.png)
and GGO_MF table 
![image](https://user-images.githubusercontent.com/29478729/70069117-8a4fab00-15f1-11ea-889c-56ed5999b958.png)

To be fixed

**Comment by combesf** [comment]
Graphical results are in agreement with textual results, at least for what is plotted in the graphics. 
The 2 categories plotted : 
"transcription coregulator activity" and 
"DNA-binding transcription factor activity"

are plotted at 3 and 9 respectively. 

On the plot, what is plotted at 0 is indeed 0 in the text file. 

So I think the question is in fact to plot on the graphics the totality of the categories that are non-null. I check the code.

**Comment by combesf** [comment]
It was that indeed. I modified the code , and the new tool is on proteore-migale to be tested. 
It just plots the results by "Count" in decreasing order, and it prints the data table results in the same way. 
it is a the very beginning of the ProteoRE tools panel on proteore-migale. 
@yvandenb  tell me when/if it is the green light to deploy on the prod instance.

**Comment by yvandenb** [comment]
Apparently the "ShowCategory" option of the barplot and dotplot function is set to 10 ? It seems that 20 (or 30) would be more informative ? 
Addon: would it be possible to modify/extend  the value of the "ontology level" (currently from 1 to 3) ? btw, I read it would be possible to restrict results at a specific go level by using "gofilter" https://yulab-smu.github.io/clusterProfiler-book/chapter5.html#test-go-at-sepcific-level  
=> to be discussed

**Comment by combesf** [comment]
Done to set the showCategory parameter to 20
To be discussed for the ontology level param. 

So test it, and tell me when green light to put the updated tool in prod instance.

**Comment by yvandenb** [comment]
Checked ! new tool version to be deployed on proteore.org

**Comment by combesf** [comment]
Done. 
Doc section to be written ASAP.
