### ISSUE TITLE
Proteore.org: update data sources file 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#262]
http://proteore.org/u/proteore/p/data-sources-2
ID_converter : David
HPA expression data: Yves
Valentin & Flo : please check these 
GO terms classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]
bioconductor-org.hs.eg.db v3.5.0
bioconductor-org.mm.eg.db v3.5.0
bioconductor-org.rn.eg.db v3.5.0
Statistical analysis of functional profiles (Human, Mouse) [goProfiles] 
bioconductor-org.hs.eg.db v3.5.0
bioconductor-org.mm.eg.db v3.5.0
Enrichment analysis for Gene Ontology (Human, Mouse, Rat)[topGO]
bioconductor-org.hs.eg.db v3.5.0
bioconductor-org.mm.eg.db v3.5.0
bioconductor-org.rn.eg.db v3.5.0

**Comment by yvandenb** [comment]
Valentin-David: did you updated release number and version listed above ?

**Comment by davidchristiany** [comment]
Not for id_converter, I will do it after the update of id_converter on proteore.org.
By the way, the 'galaxy pages' linked in the welcome page are now html pages:
- http://www.proteore.org/static/communication.html
- http://www.proteore.org/static/data_source.html

You can find it here: https://github.com/ifb-git/ProteoRE/tree/master/static

**Comment by yvandenb** [comment]
fine to me...don't forget the related issue #264
