### ISSUE TITLE
New tool: Add_Protein_Features (Rattus) - uniprot

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#263]
Same specifications as "Add protein features (Mouse) [UniProt]" 
With Taxonomy ID: 10116 for Rattus norvegicus

**Comment by yvandenb** [comment]
History "Test_Idconverter" shared with Flo, David, Val
Run using two ID lists rattus and homo sap => execution failed 
![image](https://user-images.githubusercontent.com/29478729/70865894-d2ac8880-1f62-11ea-8407-989dcaf21f7d.png)

**Comment by combesf** [comment]
Done for Rat and Human (I thought you would ...)
To be tested on migale-proteore, tool "Add protein features (3 orga) [UniProt]" (1st tool listed in the tool panel)



> History "Test_Idconverter" shared with Flo, David, Val
> Run using two ID lists rattus and homo sap => execution failed
> ![image](https://user-images.githubusercontent.com/29478729/70865894-d2ac8880-1f62-11ea-8407-989dcaf21f7d.png)


I looked at the pb. 
1st : one protein features was missing and was unable to be retrieved : it is coorected now. 
So it runs and gives a result. 

but 2d : for your rats ID, none of them match the proteome file from Uniprot ... 
I downloaded the reviewed and unreviewed proteome from rat and human. 
@davidchristiany  did you donwload the same, or only the reviewed one ? I did not find the info 
thanks.

**Comment by yvandenb** [comment]
Ok thx Flo
>for your rats ID, none of them match the proteome file from Uniprot .
This situation should not raised a "Fatal error", instead should be handled by the tool; for instance  by notifying explicitly the end-user in the history item e.g. "IDs not found" 
For your info, I submitted the Rattus ID list to Uniprot and all of these entries have a "reviewed" status...

**Comment by combesf** [comment]
Indeed the "fatal error" was due to the 1st pb, which is fixed now. 
No "fatal error" now if you run again

**Comment by yvandenb** [comment]
I 've been running again the newer version of the tool with two human IDs list => fatal error again
![image](https://user-images.githubusercontent.com/29478729/70907545-72bced00-2009-11ea-9766-830270d0fe0e.png)
Don't know why Please could you check on your side ? 
Minor change: please make the name of the output in agreement with the name of the species selected (presently Mouse whereas Human was selected)...

**Comment by combesf** [comment]
You ran the Galaxy Version 2019.12.13.2, which is nit the latest version. 
The lastest version is the 2019.12.13.3 in which the minor change you mentioned has already been fixed. 
("mouse" is not mentionned anymore)

**Comment by combesf** [comment]
You ran the Galaxy Version 2019.12.13.2, which is nit the latest version.
The lastest version is the 2019.12.16.3 in which the minor change you mentioned has already been fixed.
("mouse" is not mentionned anymore)

**Comment by yvandenb** [comment]
Sorry :-/ now it's ok...

**Comment by combesf** [comment]
I checked: on the reviewed rat proteome (not the version on the online tool) , your rat IDs are there. 
Would you want me to replace the unreviewed proteomes (human, mouse and rat) by the reviewed ones ?

**Comment by yvandenb** [comment]
Not sure I understood your comment...normally both types of ID (reviewed and unreviewed) are in Uniprot ? How features are actually retrieved from Uniprot by this tool ?

**Comment by combesf** [comment]
I'll explain you de visu. 
I just updated the proteomes files (version 2019.12.16.4) and I think results will be better ...

**Comment by combesf** [comment]
As discussed files have been updated : now it is reviewed + unreviewed. 
To be tested, than to be installed on proteore.org ?

**Comment by combesf** [comment]
PS : to be tested on migale-proteore

**Comment by combesf** [comment]
@yvandenb should I close this issue ?

**Comment by yvandenb** [comment]
Works in my hands..please add in the UserDoc section => "Data source (release date)"
"Annotations have been retrieved from UniProt.org (December 2019)." 
the url of the reference proteomes and exact release/number/version used
alos complete the "http://www.proteore.org/static/data_source.html" file accordingly
