### ISSUE TITLE
HPA source files update and data manager

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#264]
Three Proteore tools relies on HPA resources (see http://proteore.org/u/proteore/p/data-sources-2)
Get expression profiles by (normal or tumor) tissue/cell type [Human Protein Atlas] relies on " normal-" and pathology-tissues" dowloaded from HPA
while 
Add expression data (RNAseq or Immuno-assays)[Human Protein Atlas]
AND
Build tissue-specific expression dataset [Human Protein Atlas](no input required)
both rely on "ProteinAtlas" file 
However from the data manager, only two source files can be updated 
![image](https://user-images.githubusercontent.com/29478729/70705023-826bc700-1cd3-11ea-9864-6a2007e6c377.png)
although it is mentioned :"Once a database is selected, there's a second dropdown menu to select the specific file you want to update.
for 'Human Protein Atlas': 'Normal tissue', 'Pathology' and 'Full Atlas'"
Do you have an idea of what happened to the 'Full atlas' file ?

**Comment by davidchristiany** [comment]
the third option already exists, it has been commented in the code, I don't remember why but I will make it available in the next version of the data manager.
