### ISSUE TITLE
Pathways visualization [KEGG] (Galaxy Version 2019.06.27.1): total error

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#266]
history "uPE1_Male Tissue_20191210" shared 
item n°71-72

**Comment by davidchristiany** [comment]
the problem comes from the kegg pathway hsa04215, it has been corrected here for enrichmentBrowser:  
https://github.com/lgeistlinger/EnrichmentBrowser/issues/10

but not for pathview.
The only correction I can do for now is to delete this pathway in the input list, I didn't start a issue on github https://github.com/hpi-swa-teaching/PathView/issues?q=is%3Aopen+is%3Aissue because it is not supported anymore. 

So it will work with the graphviz representation (.pdf) but not with the kegg one (.jpg)

**Comment by davidchristiany** [comment]
You can try the last version on proteore-migale, let me know if it is ok for you guys.
@yvandenb @vloux @combesf

**Comment by yvandenb** [comment]
Thx david => Tested on Migale-ProteoRE
History shared with David , Flo, VL
![image](https://user-images.githubusercontent.com/29478729/71899310-b82d8f80-315b-11ea-8c03-6be289e7188d.png)

error msg: 
Error in apply(DF, c(1, 2), function(x) gsub("^$|^ $", NA, x)) : 
  objet 'DF' introuvable
Calls: main -> as.data.frame -> apply
Exécution arrêtée

**Comment by davidchristiany** [comment]
My bad, I made a mistake in the Rscript.
It is working now on proteore-migale

**Comment by yvandenb** [comment]
Tested => works fine :-)

**Comment by yvandenb** [comment]
Notify this issue to the corresponding author via BioConductor
For info: migale uses  "KEGGProfile" https://bioconductor.org/packages/release/bioc/html/KEGGprofile.html maintenu
Rem: David installed the latest version of PathView

**Comment by davidchristiany** [comment]
I've send an email to Luo Weijun, so wait and see.

**Comment by yvandenb** [comment]
A new bug observed tool version 2019.06.27.1 on proteore.org 
see history "uPE1_Male Tissue_20191210"
![image](https://user-images.githubusercontent.com/29478729/72451152-c57df600-37bb-11ea-90b0-ffe7e3cd6d09.png)

**Comment by vloux** [comment]
Same error than #251 .

**Comment by davidchristiany** [comment]
This is the same bug which has been resolved in the last version of the tool. #251
It is up to date in proteore-migale but not on proteore.org.
Do you want me to update KEGG maps visualisation on proteore.org right now ?

**Comment by yvandenb** [comment]
My bad: I thought you already did it...yes would be great, => green light :-)

**Comment by davidchristiany** [comment]
Done
