### ISSUE TITLE
Release ProteoRE 2.1 : Tool panel new version 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#267]
List of tools (ordered according to the tool panel)  and associated tasks: ongoing

**Comment by combesf** [comment]
Here is a proposal for the tool panel of the v2.1
I added if the tool is **new** or **updated**, but this is for us (not to appear in the online version)
Feel free to improve/complete ... 

**DATA MANIPULATION AND VISUALIZATION**
ID Converter (Human, Mouse, Rat) **update**
Filter by keywords and/or numerical value
Venn diagram [JVenn] **update**
Volcano Plot create a volcano plot **new**
HeatMap (Cluster and visualize the results)

**HUMAN ANNOTATION**
Get expression profiles by (normal or tumor) tissue/cell type [Human Protein Atlas]
Add expression data (RNAseq or Immuno-assays)[Human Protein Atlas]
Add protein features [neXtProt]
Get MS/MS observations in tissue/fluid [Peptide Atlas]
Get unique peptide SRM-MRM method [SRM Atlas]
Build tissue-specific expression dataset [Human Protein Atlas](no input required)

**Human, Mouse and Rat ANNOTATION**
Add protein features (3 orga) [UniProt] **new**

**GO TERMS ANALYSIS**
Statistical analysis of functional profiles (Human, Mouse) [goProfiles]
GO terms classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler] **update**
GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler] **new**
Enrichment analysis for Gene Ontology (Human, Mouse, Rat)[topGO]

**PATHWAY ANALYSIS**
Query pathway database [Reactome]
Pathways identification and coverage [KEGG]
Pathways visualization of (differentially expressed) genes/proteins [KEGG] **update**
Build Protein-Protein interaction network [BioGRID, BioPlex, HuMAP]

**Comment by yvandenb** [comment]
Great Flo!  with my suggestions included below + **en GRAS les noms d'outils qui changent**
ATTENTION!: l'ordre est important et il n'y plus que 4 sections !

DATA MANIPULATION AND VISUALIZATION
ID Converter (Human, Mouse, Rat) **updated**
Filter by keywords and/or numerical value
Venn diagram [JVenn] **updated**
**Draw Volcano Plot**  **new**
**HeatMap (Cluster and visualization)**

GET FEATURES/EXPERIMENTAL DATA
**Add protein features [UniProt, Human, Mouse, Rat]** **new**
**Add protein features [neXtProt, Human]**
Get expression profiles by (normal or tumor) tissue/cell type [Human Protein Atlas]
Add expression data (RNAseq or Immuno-assays)[Human Protein Atlas]
**Build tissue-specific expression dataset [Human Protein Atlas]**
**Get MS/MS observations in tissue/fluid [Peptide Atlas Human]**
**Get unique peptide SRM-MRM method [SRM Atlas Human]**

FUNCTIONAL ANALYSIS
**Compute functional profiles (Human, Mouse) [goProfiles]**
**Classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]** **updated**
**Biological theme comparison (Human, Mouse, Rat)[clusterProfiler]** **new**
**Enrichment analysis (Human, Mouse, Rat)[topGO]**

PATHWAY ANALYSIS
**Pathway enrichment analysis [Reactome]**
**KEGG pathways mapping and coverage [PathView]**
**KEGG pathways mapping and visualization [PathView]** **updated**
**Build Protein interaction network [BioGRID, BioPlex, HuMAP]**

**Comment by combesf** [comment]
as discussed today, I made a wiki page where to find the equivalence between sections and tools names 
there : 
https://github.com/ifb-git/ProteoRE/wiki/V2.1-tools-name-equivalence

**Comment by yvandenb** [comment]
In addition, re-organize main section as follow:
ProteoRE
Galaxy-P Tools
Text Manipulation
and then the remaining sections listed below
NB!: remove/hide the "Beta tools" section

**Comment by combesf** [comment]
> TODO list :
> 
> * [ ]  ProteoRE subSection: replace "HUMAN ANNOTATION" by "GET FEATURES/ANNOTATION

==> to be discussed tomorrow on the phone

> 
> Tool name:
> 
> * [ ]  rename "Get unique peptide SRM-MRM method [SRM Atlas]" as "Get unique peptide SRM-MRM method [Human SRM Atlas]

==> done

> * [ ]  rename "GO terms classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]" as "Classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]"

==> done. BUT we have a pb for this tool : there is 2 folders on the GitHub that can be for this tool : 
"cluster_profiler" and "GO_terms_profiles_comparison"
I think the right one is "GO_terms_profiles_comparison", but to check with David. 
And then we have to remove the wrong folder. 

> * [ ]  rename "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" as "Biological theme comparison (Human, Mouse, Rat) [clusterProfiler]"

==> cannot be done. 
On proteore , this tool has been installed from the main TS. But, when I want to update it to rename it, planemo tells me that it cannot update the tool caus it does not exist on the main TS. 
But it is there : 
https://toolshed.g2.bx.psu.edu/repository?repository_id=505eb7d912961a8f&changeset_revision=f53249651add

To be discussed. 

> 
> In addition, re-organize main section as follow:
> ProteoRE
> Galaxy-P Tools
> Text Manipulation
> and then the remaining sections listed below
> NB!: remove/hide the "Beta tools" section

**Comment by yvandenb** [comment]
there is a naming confusion in the "GO terms analysis" section (that be "Functional analysis")
![image](https://user-images.githubusercontent.com/29478729/73460330-98fbd980-4378-11ea-9a1c-64fb34cf7009.png)
1. Tool currently named "Classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler] (Galaxy Version 2020.01.24)" should be named "Biological theme comparison (Human, Mouse, Rat) [clusterProfiler]" as it does not perform "Classif and enrichment analysis"
2. Tool currently "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler] (Galaxy Version 2020.01.23)" also performs "Bioloigical theme comparison ..." but is another version and should be removed from the tool panel
3. At last, the tool that actually performs "Classif and enrichment analysis [Cluster profiler] is not there anymore ??

**Comment by combesf** [comment]
To better understand eache other : there is 4 tools in the "GO section"
My view of this section:

1st is based on goProfiles -> ok
2d is based on clusterprofiler and is the 1st level tool of clusterprofiler. The tool installed is the right one with the rught name. 
3d is based on clusterprofiler but to compare lists (compareCluster function). The tool is the right one but has to be renamed (not possible for the moment : why ?)
4th is based on topGO -> ok

**Comment by combesf** [comment]
ok Yves you're right : the 2d one is a wrong version

**Comment by yvandenb** [comment]
>2d is based on clusterprofiler and is the 1st level tool of clusterprofiler. The tool installed is the right one with the rught name.
clearly not if you look at the interface (see below) :-/
![image](https://user-images.githubusercontent.com/29478729/73465198-550cd280-4380-11ea-9fe0-f649ccadf602.png)
Please 1. check this very carefully, 2. fix it, 3. verify  and 4. then tell us

**Comment by combesf** [comment]
> there is a naming confusion in the "GO terms analysis" section (that be "Functional analysis")
> ![image](https://user-images.githubusercontent.com/29478729/73460330-98fbd980-4378-11ea-9a1c-64fb34cf7009.png)
> 
> 1. Tool currently named "Classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler] (Galaxy Version 2020.01.24)" should be named "Biological theme comparison (Human, Mouse, Rat) [clusterProfiler]" as it does not perform "Classif and enrichment analysis"
> 2. Tool currently "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler] (Galaxy Version 2020.01.23)" also performs "Bioloigical theme comparison ..." but is another version and should be removed from the tool panel

==> has been removed

> 3. At last, the tool that actually performs "Classif and enrichment analysis [Cluster profiler] is not there anymore ??

==> is back

**Comment by combesf** [comment]
I tried to rename the section name of the Tool Panel (Human annotation for ex.) , 
and the 1st section is now named "Human Annotation" and not "Data manipulation and visualization". 
I took the previous files but it stays like this ... hard to understand. 

Anyway I think that the file to change for the section name is "config/tool_conf.xml" .. 
let's talk about it tomorrow morning ...

**Comment by combesf** [comment]
> > * [x]   rename "GO terms classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]" as "Classification and enrichment analysis (Human, Mouse, Rat)[clusterProfiler]"
> 
> ==> done. BUT we have a pb for this tool : there is 2 folders on the GitHub that can be for this tool :
> "cluster_profiler" and "GO_terms_profiles_comparison"
> I think the right one is "GO_terms_profiles_comparison", but to check with David.
> And then we have to remove the wrong folder.

The wrong folder is the folder named "GO_terms_profiles_comparison". 
We'll have to delete it once all is OK on dev-migale with no confusion possible. 

> 
> > * [ ]   rename "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" as "Biological theme comparison (Human, Mouse, Rat) [clusterProfiler]"
> 
> ==> cannot be done.
> On proteore , this tool has been installed from the main TS. But, when I want to update it to rename it, planemo tells me that it cannot update the tool caus it does not exist on the main TS.
> But it is there :
> https://toolshed.g2.bx.psu.edu/repository?repository_id=505eb7d912961a8f&changeset_revision=f53249651add
> 
> To be discussed.


I just looked at the tool id : it is the same in the xml and on the main TS and on the test TS.
I  really don't understand why when I run a "planemo update" it answers me : 
"Repository [GO_terms_enrich_comparison] does not exist in the targeted Tool Shed.
Failed to update repository 'GO_terms_enrich_comparison' as it does not exist on the main Tool Shed."

It is exactly th same error message for the test TS. 

I don't know what is the best : let @davidchristiany  and @vloux look at this, or remove what exists on the TS to commit a new tool on the TS. 
Please tell me.

**Comment by davidchristiany** [comment]
I updated the tool panel of proteore-migale, tell me if it is ok for you guys.

**Comment by yvandenb** [comment]
thx David... Two things that remain to be fixed:
1. Add protein features [neXtProt, Human] is missing 
2. "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" to be renamed and/or replaced by "Biological theme comparison (Human, Mouse, Rat)" + gitHub to be cleaned (2 versions of this tool seems to coexist)

**Comment by davidchristiany** [comment]
I added "Add protein features [neXtProt, Human] is missing".
I let @combesf rename "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" and clean the git hub repository as I am not to sure what to do.

**Comment by yvandenb** [comment]
Selecting RNAseq and the version 22/01/2020, this ouptut is returned:
![image](https://user-images.githubusercontent.com/29478729/73658298-6150a280-4694-11ea-9d33-665f0d90f4c1.png)
While selecting RNAseq and the version 23/10/2018, I got the following ouput (that is the one we expected):
![image](https://user-images.githubusercontent.com/29478729/73658422-95c45e80-4694-11ea-9a70-506ed8962e59.png)
I suspect a new confusion, in the source file used to retrieve the information
As a reminder: 
Release date 23/10/2018: files used are : normal_tissue.tsv (for IHHC) and rna_tissue.tsv (for RNASeq); 
Release date 22/01/2020: files used are: normal_tissue.tsv (for IHHC) and rna_tissue_consensus.tsv (for RNASeq, HPA-GTEx-FANTOM5);

**Comment by combesf** [comment]
About the "renaming" of this tool I posted on friday on this issue:
 
> > > * [ ]    rename "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" as "Biological theme comparison (Human, Mouse, Rat) [clusterProfiler]"
> > 
> > 
> > ==> cannot be done.
> > On proteore , this tool has been installed from the main TS. But, when I want to update it to rename it, planemo tells me that it cannot update the tool caus it does not exist on the main TS.
> > But it is there :
> > https://toolshed.g2.bx.psu.edu/repository?repository_id=505eb7d912961a8f&changeset_revision=f53249651add
> > To be discussed.
> 
> I just looked at the tool id : it is the same in the xml and on the main TS and on the test TS.
> I really don't understand why when I run a "planemo update" it answers me :
> "Repository [GO_terms_enrich_comparison] does not exist in the targeted Tool Shed.
> Failed to update repository 'GO_terms_enrich_comparison' as it does not exist on the main Tool Shed."
> 
> It is exactly th same error message for the test TS.
> 
**> I don't know what is the best : let @davidchristiany and @vloux look at this, or remove what exists on the TS to commit a new tool on the TS.
> Please tell me.**


So @davidchristiany when you write:


> I let @combesf rename "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]" and > 
> clean the git hub repository as I am not to sure what to do.
 
the answer is that I don't manage to rename this tool since last week.

**Comment by davidchristiany** [comment]
OK I can try to change the name of "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]", everything is up to date on github ? 

For  "GO_terms_profiles_comparison", I think it was the first version of your tool @combesf, the one we did together when you came at Migale ? 
If that's the case we can delete it. (anyway we can still find it in github history)

**Comment by combesf** [comment]
> OK I can try to change the name of "GO terms enrich comparison (Human, Mouse, Rat)[clusterProfiler]", everything is up to date on github ?

==> Yes, in the "GO_terms_enrich_comparison" folder 
If you find the solution, please let me know ... !!

> 
> For "GO_terms_profiles_comparison", I think it was the first version of your tool @combesf, the one we did together when you came at Migale ?

==> yes it was indeed. 

> If that's the case we can delete it. 

==> I agree. 

> (anyway we can still find it in github history)

**Comment by davidchristiany** [comment]
The .shed.yml is missing in "GO_terms_enrich_comparison": 
https://github.com/ifb-git/ProteoRE/tree/master/tools/GO_terms_enrich_comparison

@combesf Can you add it please ?

**Comment by combesf** [comment]
@davidchristiany  done

**Comment by combesf** [comment]
I can put it on the testTS and mainTS, and install it on proteore-migale if you want ?

**Comment by davidchristiany** [comment]
I updated https://github.com/ifb-git/ProteoRE/tree/master/tools/GO_terms_enrich_comparison with the new name: Biological theme comparison

The problem you encountered was linked to the name in the .shed.yml:
it was proteore_go_terms_profiles_comparison instead of proteore_go_terms_enrich_comparison

**Comment by combesf** [comment]
ok thanks for the info. I is my fault, sorry. 

Do you or do I continue ?

**Comment by combesf** [comment]
ok I see it is updated on proteore-migale

**Comment by yvandenb** [comment]
Fixed by David
