### ISSUE TITLE
Venn diagram tool problem

### ISSUE THREAD

**Issue by vloux** [ifb-git/ProteoRE#268]
Reported by Melissa DUSSOYER <melissa.dussoyer@ibcp.fr> :

> Dear ProteoRE team,
> 
> I'm contacting you because of a problem encountered with the tool "Venn Diagram" of ProteoRE platform.
> 
> When I use this tool to compare two sets of Proteins IDs (or more), the list of common proteins obtained by clicking on the schematic representation differs from the one of the text output file (loss of one protein, always the last of the "common" list of the schematic representation). I join a picture to illustrate the problem to this e-mail.
> 
[Proteore_Vennproblem_illustration.pdf](https://github.com/ifb-git/ProteoRE/files/4039588/Proteore_Vennproblem_illustration.pdf)
> I've run different jobs with this tool, using different datasets; the problem always occurs.
> I've checked the parameters to fill in before running the Venn analyse, they seem OK, and I didn't find any other explanation. Have you ever heard about this problem, or do you have advices to give me to avoid this loss ?
> 
> Thank you in advance for your answer,
> Regards,
> 
> --
> Mélissa Dussoyer
> PhD Student in Matrix Biology

> 
> Je vous ai dressé un historique répétant les analyses que j'ai faites ces deux derniers jours, qui correspondent aux images transmises précédemment.
> Cela m'a permis de vos faire un historique plus léger et cohérent (je travaille sur l'ancien historique actuellement, et l'enrichis pas mal, donc cela pourrait être compliqué à suivre). Il est nommé "Tests outil Venn", et mon nom public de compte est "md_ibcp".
> 
> Pour vous aider à comprendre, j'ai :
> - importé un fichier (le numéro 1) avec 3 colonnes, correspondant à 3 réplicats à comparer,
> - importé le fichier 9, qui correspond à la liste des ID communs entre ces 3 réplicats, que j'ai dressée manuellement,
> - mené une comparaison de type Venn sur le fichier 1 (fichiers 3 & 4 générés). Cela illustre la première perte de l'ID P47857 entre les fichiers 3 et 4.
> -mené une comparaison entre la colonne 6 du fichier 4 et la liste des IDs communs dans mes triplicats que j'ai dressée manuellement (fichiers 10 & 11 générés), qui illustre une nouvelle perte (ID P21550). D'où la différence de 2 protéines entre la liste issus du fichier 4 et la manuelle, due aux 2 pertes successives.
> 
> J'espère que cela vous aidera à comprendre, n'hésitez pas à me recontacter si besoin est.
> 
> Belle soirée,
> Cordialement,
> 
>

**Comment by davidchristiany** [comment]
I have fixed the issue in venn diagramm, it was due to an error while adding the NA to have the same number of lines for all columns. I wasn't taking into account the header, so one line was missing ...
You can try the last version on proteore-migale.
Someone send an email to Melissa DUSSOYER ?

**Comment by davidchristiany** [comment]
@vloux ?

**Comment by vloux** [comment]
sorry for delay; Could you deploy it on proteore.org ?

**Comment by davidchristiany** [comment]
Done !
But there's an issue on proteore.org, every job end with that error:
`Instance <ToolShedRepository at 0x7f6e4cb53790> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)`

Any ideas ?

**Comment by vloux** [comment]
Can't reproduce it. Have you rebooted ?

**Comment by davidchristiany** [comment]
yes

**Comment by davidchristiany** [comment]
OK after a second reboot it works fine.
