### ISSUE TITLE
fichier source HPA, data manager et outils les utilisant

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#269]
3 fichiers HPA sont gérés par le data manager: 
1. Le fichier source HPA : https://www.proteinatlas.org/download/proteinatlas.tsv.zip nommé "Full Atlas" dans le data manager est utilisé par l'outil "Add expression data"
=> contriarement aux autres outils manipulant les sources HPA, il n'y a pas d'option dans le xml de l'outil qui permet de gérer la version du source file, si je fais un update ; par ex ajouter une select box: "select the HPA source file version" 
=> replace "Full Atlas" by "Full Protein Atlas"
2. Meme constat avec l'outil "Build tissue-specific expression dataset ", pas de moyen de sélectionner la version via l'interface et on ne connait pas le nom *exact* du source file utilisé
=> ajouter cette option dans l'interface
=> documenter dans le data manager (partie description et quel outil utilise quel fichier) 
3. "Get expression profiles by (normal or tumor)" est OK pour afficher les versions via son interface; la partie userDoc doit préciser, le pointeur fichier - actuellement il est mentionné: "Both normal and tumor tissues data are based on the Human Protein Atlas version 18.1 and Ensembl version 88.38. More information: https://www.proteinatlas.org/about/download" => l'URL doit être exact

**Comment by davidchristiany** [comment]
For "get expression level" tool, on which columns do you want to filter results for full atlas option ? 
Reliability (IH) and Reliability (IF) ?

**Comment by yvandenb** [comment]
>For "get expression level" tool,
for sake of clarity, which tool are you referring to ?

**Comment by davidchristiany** [comment]
I meant "Get expression profiles"

**Comment by davidchristiany** [comment]
I can also modify "Add expression data", for now this tool use a csv in his tool_directory and not a file made by the data manager. It looks like a subset of a "full Atlas " csv file

**Comment by yvandenb** [comment]
On which data source (i.e. file name) "Get expression profiles" relies on ? By the way, the option "Reliability score" of this tool referred to the column  "Reliability (IH)"

"Add expression data" actually relies on  http://www.proteinatlas.org/download/proteinatlas.tab.gz; I think it would more practical to manage this file via the data manager, but this implies a post-processing of this file once downloaded - would it be easily feasible ?

**Comment by davidchristiany** [comment]
"Get expression profiles" relies on HPA normal and tumor tissue files, it is already working with the data manager, I thought you wanted to add a third option with the "full atlas" file, my bad.

I can easily modify "Add expression data" in order to make it work with the data manager. The best solution is to adapt this tool to work with the source file "full atlas" (non processed) instead of modifying the data manager to create a specific file since several tools relies on the "full atlas" file.

I hope I am clear enough

**Comment by yvandenb** [comment]
OK for "Get expression profiles" - please rename the header "Normal tissue HPA version 18.1" by "HPA source files version"  
![image](https://user-images.githubusercontent.com/29478729/72888162-59484880-3d0d-11ea-8ce7-b064e68a3ecb.png)

Green light to modify "Add expression data" as you proposed; given that, the interface should be modified accordingly by adding an option i.e. "HPA source file version" allowing for the selection of each version of "proteinatlas.tab.gz" donwloaded and installed by the data manager. Please note that the current version of this source file is "HPA version 18.1 and Ensembl version 88.38" (as mentionned in the user doc section) and that the new version will now be "Human Protein Atlas version 19.1" as documented here :https://www.proteinatlas.org/about/download, once downloaded via the data manager

**Comment by davidchristiany** [comment]
For Add expression data: 
Several columns are not present anymore in the full atlas file, such as:
- RNA tissue category
- Subcellular location
- RNA TS TPM
- TPM max in non-specific

What do we do ?

**Comment by yvandenb** [comment]
Simply because columns of this table have been renamed, and this file has been considerably enriched-extended, however, and fortunately, (most of) the information are still there;
In the current version of https://www.proteinatlas.org/download/proteinatlas.tsv.zip
"RNA tissue category" is now "RNA tissue specificity" (Column N)
"Subcellular location" still has the same name "Subcellular location" (Column AX)
"RNA TS TPM" is now "RNA tissue specific NX" (Column N)
only "TPM max in non-specific" has actually been removed :-(
Let's talk about this by phone => tomorrow 11 am, would it be possible ?

**Comment by davidchristiany** [comment]
>  Let's talk about this by phone => tomorrow 11 am, would it be possible ?

Yes, no problem.
