### ISSUE TITLE
proteore-migale : Volcano-Plot, deprecated dependencies 

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#273]
History "TEST_YV" shared with Val/David/flo:
![image](https://user-images.githubusercontent.com/29478729/73752676-a7276c80-4761-11ea-8450-36e9a70aab3a.png)
Warning message:
As of rlang 0.4.0, dplyr must be at least version 0.8.0.
✖ dplyr 0.7.8 is too old for rlang 0.4.1.
ℹ Please update dplyr with `install.packages("dplyr")`. 
Warning messages:
1: The `printer` argument is deprecated as of rlang 0.3.0.
This warning is displayed once per session. 
2: In Ops.factor(fdr, opt$signif_thresh) : '<' not meaningful for factors
3: In Ops.factor(logFC, opt$lfc_thresh) : '>' not meaningful for factors
Error in Math.factor(Pvalue) : 'log10' not meaningful for factors
Calls: print ... scales_add_defaults -> lapply -> FUN -> Math.factor

**Comment by vloux** [comment]
Tool on the latest release of the TS( 73b8cb5bddcd , Galaxy Version 0.0.3) :

Dependencies installed by conda :

```
Volcano Plot | /projet/galaxyprod/proteore2/conda/d/_conda/envs/mulled-v1-8ddc0b2c9894ff569738648322f142b571b15043fb38a6c38d71de84cd968c11 | r-ggplot2 | 3.1.0 | Conda | True |  
-- | -- | -- | -- | -- | -- | --
  |   | /projet/galaxyprod/proteore2/conda/d/_conda/envs/mulled-v1-8ddc0b2c9894ff569738648322f142b571b15043fb38a6c38d71de84cd968c11 | r-ggrepel | 0.8.0 | Conda | True |  
  |   | /projet/galaxyprod/proteore2/conda/d/_conda/envs/mulled-v1-8ddc0b2c9894ff569738648322f142b571b15043fb38a6c38d71de84cd968c11 | r-dplyr | 0.7.8 | Conda | True |  
  |   | /projet/galaxyprod/proteore2/conda/d/_conda/envs/mulled-v1-8ddc0b2c9894ff569738648322f142b571b15043fb38a6c38d71de84cd968c11 | r-getopt | 1.20.2 | Conda | True
```

Tried uninstall -Re-install. Without effect

**Comment by vloux** [comment]
Correction, error doesn't seem to be correlated with the warning in the logs.
It works with test data (History "Test VolcanoPlot" shared with @yvandenb ).
Something in the input file or parameters ?

**Comment by yvandenb** [comment]
Volcano-Plot tool (newest version 0.03) is not accessible on proteore-migale ? Please could you help ?
