### ISSUE TITLE
KEGG pathways mapping and visualization [PathView]: execution halted

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#274]
history shared with David & Flo 
See snapshot 
![image](https://user-images.githubusercontent.com/29478729/75355913-7db8b700-58af-11ea-94a2-b87407206126.png)
error message: 
Error in seq.default(from = limit[1], to = limit[2], length = bins + 1) : 
  'from' must be a finite number
Calls: main ... withCallingHandlers -> pathview -> node.color -> seq -> seq.default
Execution halted
Rem: Quantitative value (Fold Change) used are in the form of both negative and positive values

**Comment by yvandenb** [comment]
runned again using another tool version => new error msg
toolshed.g2.bx.psu.edu/repos/proteore/proteore_maps_visualization/kegg_maps_visualization/2020.01.23.
Failed with error:  ‘there is no package called ‘org.Mm.eg.db’’
Error in loadNamespace(name) : there is no package called ‘BiocManager’
Calls: main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

I didn't find "package called ‘org.Mm.eg.db’’ in R. the source code

**Comment by davidchristiany** [comment]
It is a bug present only in the 2020.01.24 version, it has been corrected in following versions.
I uninstall the 2020.01.24 version from proteore.org

You have to use the last version: 2020.02.06

**Comment by yvandenb** [comment]
Thx David - two more questions:
![image](https://user-images.githubusercontent.com/29478729/75436562-0e959e00-5955-11ea-920d-898a0c7cb04a.png)
Five versions are listed, but "2020.02.06" not found ?
the main header is : "KEGG pathways mapping and visualization [PathView] (Galaxy Version 2020.01.23)" however no "2020.01.23" seems to be available from the list of version ?

**Comment by davidchristiany** [comment]
You're right, I looked at another history :/ 
I'll take a look

**Comment by davidchristiany** [comment]
The first error:
```
error message:
Error in seq.default(from = limit[1], to = limit[2], length = bins + 1) :
'from' must be a finite number
Calls: main ... withCallingHandlers -> pathview -> node.color -> seq -> seq.default
Execution halted
```
seems to occur when you select the wrong species, here Human instead of Mouse.

The second one is obviously an error with the requirement:
```
Failed with error:  ‘there is no package called ‘org.Mm.eg.db’’
Error in loadNamespace(name) : there is no package called ‘BiocManager’
Calls: main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Exécution arrêtée
```
I'm working on it

**Comment by davidchristiany** [comment]
The error was caused by the pathway id 'mmu04723'.
It is now removed from the pathway ids list in input with the pathway 'hsa04215'.
I added an error message when an id is removed from the input and another when there's no pathway ids left after removing the bad ones:

![Capture du 2020-03-02 10-13-37](https://user-images.githubusercontent.com/39336353/75661934-88d46400-5c6e-11ea-8415-eaaec73ecd78.png)

I also added a warning in the doc:
![Capture du 2020-03-02 10-14-48](https://user-images.githubusercontent.com/39336353/75662000-a99cb980-5c6e-11ea-90cd-adc44dc23276.png)

You can test this update on proteore-migale.

**Comment by yvandenb** [comment]
tested in migale-proteore
history "Test-KEGGTOOLS" shared with David
doesn't work for mouse specie (see snapshot):
![image](https://user-images.githubusercontent.com/29478729/75967104-9cc8d180-5ecb-11ea-98c2-312ff5b0336a.png)
Also tested for human species =>  no maps created, see item n°7 and 8 _ wonder why ?

**Comment by davidchristiany** [comment]
It was due to NA in the quantitative data column.
I modified the tool to handle it.
It works now with the last version, you can test it on proteore-migale

**Comment by yvandenb** [comment]
Tested the two jobs (one using mouse dataset, another one a human dataset) => both worked ! :-)
Thx David -> please can you deployed this new version in proteore.org

**Comment by davidchristiany** [comment]
I updated kegg maps visualization on proteore.org
