### ISSUE TITLE
migale-proteore: "The cluster DRM system terminated this job"

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#275]
history "Test_KEGGTOOLS" shared with David and Valentin
![image](https://user-images.githubusercontent.com/29478729/75994913-f2b56d80-5efb-11ea-98fb-fc874d06539b.png)
whatever the tool launched, I got the same error msg...

**Comment by vloux** [comment]
Solved (remount of /projet/galaxyprod dir on cluster)
