### ISSUE TITLE
missing column on add expression data output

### ISSUE THREAD

**Issue by davidchristiany** [ifb-git/ProteoRE#276]
Gene description is missing when this column is selected in the last version (2020.01.24)

**Comment by davidchristiany** [comment]
I fixed the issue and commit the last tool verion to github.
Right now, I can't upload the tool update on test toolshed because of an error:
`Could not update proteore_expression_rnaseq_abbased
('Connection aborted.', error(54, 'Connection reset by peer')), 0 attempts left: 
Repository [proteore_expression_rnaseq_abbased] does not exist in the targeted Tool Shed.
Failed to update repository 'proteore_expression_rnaseq_abbased' as it does not exist on the test Tool Shed.`

I think it's comming from the testtoolshed itself, I'll try later.

@combesf don't you had the same issue ?

**Comment by davidchristiany** [comment]
I didn't resolved this issue on the testtoolshed, it worked on the main toolshed.
I update this tool on proteore-migale, you can test it beore installing it on proteore.org.
@yvandenb @combesf

**Comment by yvandenb** [comment]
Tested on migale-proteore => OK "gene description" field is now present using the "HPA full atlas 06/04/2020" version - also tested with "HPA Full Atlas 23/10/2018" and worked as well :-)
NB: the release date of the HPA version (latest one) has changed, don't forget to check the version release date in the USerDoc section to make it consistent with

**Comment by davidchristiany** [comment]
You mean the name of the release in proteore.org ? 
Put '06/03/2020 (v19.3)' instead of 'HPA full atlas 28/04/2020' ?

**Comment by yvandenb** [comment]
Well, in the userDoc section is mentionned: "HPA source file version (release date)

Release date 23/10/2018: data are based on the Human Protein Atlas version 18.1 and Ensembl version 88.38
Release date 21/01/2020: a subset of the data in the Human Protein Atlas version 19.1" 
However, the release date has now changed and I don't how to document this information once an update is done using the data manager...let's say, forget it at the moment and deploy the new version of this tool as it, would be fine :-)

**Comment by davidchristiany** [comment]
The only way to change the user doc section is to modify the xml file manually.
Same thing for the release name in the drop down menu.
I will update it on proteore.org and change the name in the down menu.
