### ISSUE TITLE
Get MS/MS observations in tissue/fluid: Fatal error: Exit code 1 ()

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#277]
instance: www.proteore.org
History shared with David & Valentin
![image](https://user-images.githubusercontent.com/29478729/80511233-1f29bb00-897c-11ea-8a08-77101246a5d6.png)

**Comment by davidchristiany** [comment]
I update this tool on proteore migale:
http://migale.jouy.inra.fr/proteore/root?tool_id=testtoolshed.g2.bx.psu.edu/repos/proteore/proteore_ms_observation_pepatlas/retr_pepatlas1/2020.04.30

to test

**Comment by yvandenb** [comment]
tested on migale-proteore => works fine ! :-) please could you deploy it on proteore.org
Warning: two versions of this tool are now displayed on the tool panel, don't know why ??
![image](https://user-images.githubusercontent.com/29478729/80732818-20d6b880-8b0d-11ea-8985-d0fe64a34f67.png)

**Comment by davidchristiany** [comment]
That's because one is from the main toolshed and one from the testtoolshed, so it is two different tools for Galaxy. It's temporary, I will remove the one from the testtoolshed.

**Comment by davidchristiany** [comment]
Done
