### ISSUE TITLE
Data manager : HPA resources and "Get expression profiles" -> file not found

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#279]
History shared with David 
![image](https://user-images.githubusercontent.com/29478729/80977497-1aa24e00-8e25-11ea-946d-febdd3ca383e.png)
```
Get Expression profiles" tool  - selection of "HPA normal tissue 03/02/2020" version -> 
Error in read_file(args$ref_file, TRUE) : File not found !
Calls: main -> read_file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_expression_levels_by_tissue/56c93d1fc8fd/proteore_expression_levels_by_tissue/tool-data/HPA_normal_tissue_03-02-2020.tsv': No such file or directory
Execution halted
```
As the file was not found, I updated this HPA file using the data manager, now OK - don't know why the previous release file is not found ? this one (i.e. 03/02/2020 version) should now be removed

**Comment by yvandenb** [comment]
another bug identified (by galaxy-p team); https://docs.google.com/document/d/1N_cgQAmrF5PobjWalr7Qz-aM8qr2p0WVZ-OeZXdk-m0/edit?usp=sharing
using "Add expression data" tool and selecting "HPA full atlas 2020" as HPA source file version, the "gene description" is not returned in the output file even if selected ? of note, this is not the case when using the "HPA full Atlas 2018" source file

**Comment by davidchristiany** [comment]
This bug has already been fixed in the last version of "add expression data" tool: 2020.04.06
In the shared history (google doc) this is the previous version used: 2020.01.24
Maybe we should remove it from proteore.org

**Comment by yvandenb** [comment]
>Maybe we should remove it from proteore.org
Yes for sure, yet this version is not visible anymore from my proteore.org interface, neither the latest ?? What's going on ?
![image](https://user-images.githubusercontent.com/29478729/83658527-9e855c80-a5c2-11ea-9ac0-e07b3138f351.png)

**Comment by davidchristiany** [comment]
I don't know I'm on it, I didn't remove anything, just updated the list.

**Comment by davidchristiany** [comment]
@yvandenb Can you tell me which source file is missing on Add expression data and get expression profile please ?
I will put it back manually.

**Comment by yvandenb** [comment]
What about doing this myself by using the data manager ?  btw the file name is "full protein Atlas", the  version I updated should be in May (see my first post above)

**Comment by davidchristiany** [comment]
You can use the data manager, but try one by one and refresh the corresponding data table (admin) to see if something happen.  

> btw the file name is "full protein Atlas"

For add expression data ?

**Comment by yvandenb** [comment]
logged as admin; updating "Full Atlas" file using the data manager (via admin interface)...what I see in the "Add_expression_data" GUI
![image](https://user-images.githubusercontent.com/29478729/83753679-03948d00-a66b-11ea-91dd-5de139f44194.png)

**Comment by yvandenb** [comment]
now logged as "yvdb" running again "Add expression data" with the new HPA file version (04/06/2020) => all features (fields)requested are there :-)
