### ISSUE TITLE
install tool from ToolShed in ProteoRE

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#282]
please could you install the following tool (fgsea) in ProteoRE 

https://toolshed.g2.bx.psu.edu/repository?repository_id=64b93438c1043746  

Placed under the "Functional analysis" section of the tool panel, with the following title "Fast gene set enrichment analysis [fgsea]"

**Comment by davidchristiany** [comment]
A which position in the "Functional analysis" section do you want it ? At the end ?

**Comment by yvandenb** [comment]
>at the end ? 
Yes, this would be fine !

**Comment by davidchristiany** [comment]
it is installed now

**Comment by yvandenb** [comment]
"gsea" not at the right place : 
![image](https://user-images.githubusercontent.com/29478729/88896437-1fbb4180-d24a-11ea-9a75-96c9f395da23.png)
please could you arrange that ?
